project:
  type: book

book:
  title: "NLP avec R pour les sciences sociales"
  author:
    name: Sophie Balech
    email: sophie.balech@u-picardie.fr
    affiliation: IAE Amiens - Université Picardie Jules Verne
  date: 2024-05-28
  date-format: "DD/MM/YYYY"
  language: fr  
  license: "(C) EQW SB23-24"
  cover-image: cover.png
  search: true
  repo-url: https://github.com/SB427/NLP_ED/
  repo-actions: [edit]
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Niveau 1 : Initiation"
      chapters: 
        - chapter1.qmd
        - chapter2.qmd
        - chapter3.qmd

    - part: "Niveau 2 : Approfondissements"
      chapters: 
        - chapter4.qmd
        - chapter5.qmd
  appendices:
    - webscraping.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute: 
  freeze: auto

