# Introduction {.unnumbered}

Ceci est le support pour le cours "NLP avec R pour les sciences sociales" réalisé auprès des doctorants de l'école doctorale SHS de l'UPJV.

L'objectif est de donner aux apprenants des méthodes et outils pour traiter de larges corpus de texte pour répondre à leur problématique de recherche.

L'environnement de traitement des données est R et Rstudio.

[Ici](https://sb427.github.io/NLP_CRIISEA/NLP_CRIISEA.html#/title-slide), une présentation en guise d'introduction.


## Ressources en ligne :

[R et RStudio]{style="color:red"}

-   <https://www.r-project.org/>

-   <https://rstudio.com/products/rstudio/>

[Des ressources en ligne]{style="color:green"}

-   [Introduction à R et au tidyverse](https://juba.github.io/tidyverse/index.html)

-   [R for data science](https://r4ds.had.co.nz/)

-   [Hands-On Programming with R](https://rstudio-education.github.io/hopr/)

-   [Text mining with R](https://www.tidytextmining.com/index.html)

-   [Tutoriels Quanteda](https://tutorials.quanteda.io/introduction/)

-   [Les techniques du NLP pour la recherche en sciences de gestion](https://www.researchgate.net/publication/337744581_NLP_text_mining_V40_-_une_introduction_-_cours_programme_doctoral)

-   [NLP avec r et en français - un Manuel synthétique](https://benaventc.github.io/NLPBook/)

-   [Quarto pour communiquer](https://quarto.org/)

-   Le séminaire du Collège de France : [Apprendre les langues aux machines - B. Sagot](https://www.college-de-france.fr/fr/agenda/seminaire/apprendre-les-langues-aux-machines)